import type { ReaderLabels } from './types';

export const DEFAULT_LABELS: ReaderLabels = {
  back: 'Back',
  contents: 'Contents',
  settings: 'Aa',
  backMatter: 'Back matter',
  inChapter: 'in chapter',
  ofBook: 'of book',
  leftInChapter: 'left in chapter',
  leftInBook: 'left in book',
  about: 'about',
  lessThanAMinute: 'less than a min',
  hourShort: 'hr',
  minuteShort: 'min',
  chapter: 'Chapter',
  page: 'page',
  backTo: 'Back to',
  furthestTitle: 'Pick up where you left off?',
  furthestBody: 'You were further along on another device.',
  go: 'Go',
  dismiss: 'Stay here',
  theme: 'Theme',
  fontSize: 'Size',
  font: 'Font',
  spacing: 'Spacing',
  margins: 'Margins',
  align: 'Align',
  brightness: 'Brightness',
  volumeKeys: 'Volume keys turn pages',
};
